name: aylon_frontend
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  liquid_swipe: ^1.3.1
  flare_flutter: ^2.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flare_splash_screen: ^3.0.1
  flappy_search_bar: ^1.7.2
  pull_to_refresh: ^1.5.8
  flutter_icons: ^1.0.0+1
  flutter_sticky_header: ^0.4.2
  carousel_slider: ^1.3.0
  # connectivity: any
  # fluttertoast: ^2.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/font/Product_Sans_Bold.ttf
        - asset: assets/font/Product_Sans_Regular.ttf
  
    - family: Pacifico
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf
