const String TEXT_INPUT_TYPE = 'TEXT_INPUT_TYPE';
const String DROP_DOWN_TYPE = 'DROP_DOWN_TYPE';

//* ROUTE NAMES
const String SETTING_PAGE = 'SETTING_PAGE';
const String DISCOVER_PAGE = 'DISCOVER_PAGE';
const String HOME_PAGE = 'HOME_PAGE';
const String LIKE_PAGE = 'LIKE_PAGE';
const String NOTIFICATION_PAGE = 'NOTIFICATION_PAGE';
const String SINGLE_POST_PAGE = 'SINGLE_POST_PAGE';
const String SHOP_PAGE = 'SHOP_PAGE';
